### PR TITLE
Added a primitive CS-Studio interface.

### PR DESCRIPTION
**Pull request by SkyToGround**
A simple and primitive CS-Studio view/interface for use with the ADC-boxes. I will try to improve it as the IOC improves.

### CODE REVIEW

**Comment by waynelewis** [comment]
GUI files normally live in a path like `dmsc_detector_interfaceApp/op/bob`. I'll merge this request, but we should move them to this standard path soon.

**Comment by SkyToGround** [comment]
Ok, I have already made some minor changes so I will move the files in the next pull-request. Seeing as I am not familiar with CS-Studio, is the _.project_-file needed as well?

**Comment by waynelewis** [comment]
The .project file is needed if you want to import into CS-Studio as a project.

You could also look at these repos:

https://bitbucket.org/europeanspallationsource/ess-opi-common/src/master/
https://bitbucket.org/europeanspallationsource/ess-opi-main/src/master/

I'm working on this as an idea for how to manage custom and common displays. It's how the displays at Utgård are being managed. You could add your templates to ess-opi-common, and then add to the ics/hwi/hzb/v20/main_v20.bob in ess-opi-main to launch them.

**Comment by waynelewis** [comment]
Let me know if you need permission for those repos. They're ESS bitbucket, so the standard group permissions apply.

**Pull request merged**
